"""
Django settings for mountain_passes project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import environ
from pathlib import Path

# Путь к корневой папке проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Инициализация environ для использования переменных окружения
env = environ.Env()
env.read_env(BASE_DIR / '.env')

# Проверка загрузки переменных окружения
# print("BASE_DIR:", BASE_DIR)
# print("Current Directory:", Path.cwd())
# print(".env file location:", BASE_DIR / '.env')
# print("DB_NAME:", env('DB_NAME', default=None))
# print("DB_USER:", env('DB_USER', default=None))
# print("DB_PASSWORD:", env('DB_PASSWORD', default=None))
# print("DB_HOST:", env('DB_HOST', default=None))
# print("DB_PORT:", env('DB_PORT', default=None))

# Определение базовых настроек
SECRET_KEY = env('SECRET_KEY', default='django-insecure-#hzhsg&8(w=9)6*jaut-@0t)9!y+ss0g_h5+qxmg#)6b0n5muu')
DEBUG = env.bool('DEBUG', default=True)
ALLOWED_HOSTS = []

# Настройка базы данных
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',  # Добавляем drf_yasg для документации Swagger
    'passes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mountain_passes.urls'

# Определение шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mountain_passes.wsgi.application'

# Валидация паролей
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Интернационализация
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Статические файлы (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Настройка автоматического поля первичного ключа
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для медиа-файлов
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Настройки для drf-yasg (Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Mountain Passes API',
    'DESCRIPTION': 'API documentation for managing information about mountain passes.',
    'VERSION': '1.0.0',
    'CONTACT': {
        'email': 'admin@example.com',
    },
}